"""Add Project and Issue models.

Revision ID: b47ab726b3c1
Revises: ee542e6c378d
Create Date: 2026-03-12 00:23:13.320938

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b47ab726b3c1"
down_revision: str | Sequence[str] | None = "ee542e6c378d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("key", sa.String(length=10), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["auth_user.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("project_id"),
    )
    op.create_index(op.f("ix_project_key"), "project", ["key"], unique=True)
    op.create_table(
        "issue",
        sa.Column("issue_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column(
            "type",
            sa.Enum("EPIC", "STORY", "TASK", "BUG", name="issuetype"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("TODO", "IN_PROGRESS", "IN_REVIEW", "DONE", name="issuestatus"),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("LOWEST", "LOW", "MEDIUM", "HIGH", "HIGHEST", name="issuepriority"),
            nullable=False,
        ),
        sa.Column("assignee_id", sa.String(length=36), nullable=True),
        sa.Column("reporter_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"], ["auth_user.user_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["issue.issue_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["project_id"], ["project.project_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"], ["auth_user.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("issue_id"),
    )
    op.create_index(
        op.f("ix_issue_assignee_id"), "issue", ["assignee_id"], unique=False
    )
    op.create_index(op.f("ix_issue_parent_id"), "issue", ["parent_id"], unique=False)
    op.create_index(op.f("ix_issue_project_id"), "issue", ["project_id"], unique=False)
    op.create_index(
        op.f("ix_issue_reporter_id"), "issue", ["reporter_id"], unique=False
    )
    op.create_index(op.f("ix_issue_status"), "issue", ["status"], unique=False)
    op.create_index(op.f("ix_issue_type"), "issue", ["type"], unique=False)
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column(
            "create_time",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "update_time",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("projects_pkey")),
    )
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=True)
    op.drop_index(op.f("ix_issue_type"), table_name="issue")
    op.drop_index(op.f("ix_issue_status"), table_name="issue")
    op.drop_index(op.f("ix_issue_reporter_id"), table_name="issue")
    op.drop_index(op.f("ix_issue_project_id"), table_name="issue")
    op.drop_index(op.f("ix_issue_parent_id"), table_name="issue")
    op.drop_index(op.f("ix_issue_assignee_id"), table_name="issue")
    op.drop_table("issue")
    op.drop_index(op.f("ix_project_key"), table_name="project")
    op.drop_table("project")
    # ### end Alembic commands ###
